name: khono_recruite
description: A recruitment app with modern red & white UI and authentication flow.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0
  syncfusion_flutter_charts: ^32.1.23
  flutter_web_auth: ^0.6.0
  percent_indicator: ^4.2.5
  dio: ^5.9.0
  open_file: ^3.5.10
  dotted_border: ^3.1.0
  url_launcher: ^6.3.2
  syncfusion_flutter_calendar: ^32.1.23
  flutter_staggered_animations: ^1.1.0
  table_calendar: ^3.1.0
  google_fonts: ^7.1.0
  font_awesome_flutter: ^10.9.1
  image_picker: ^1.2.0
  web_socket_channel: ^3.0.3
  firebase_auth: ^6.1.0
  firebase_core: ^4.1.1
  google_sign_in: ^7.2.0
  lottie: ^3.3.1
  go_router: ^17.0.1
  socket_io_client: ^3.1.4
  fl_chart: ^1.1.0
  vector_math: ^2.1.4
  file_picker: ^10.3.3
  qr_flutter: ^4.1.0
  webview_flutter: ^4.10.0
  webview_flutter_web: ^0.2.3
  firebase_ai: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
